### ISSUE TITLE
Pytest version requirement

### ISSUE THREAD

**Issue by smarlowucf** [numirias/pytest-json-report#59]
I tried with pytest as old as 3.10.1 and it seems to work fine. Is there a reason to lock it at pytest>=4.2.0? If it works with older pytest versions it'd be helpful to not have a minimum version lock.

**Comment by numirias** [comment]
Makes sense. At the same time I want to avoid getting obscure bug reports or patches for outdated versions, so I'd not be comfortable dropping a minimum requirement entirely.

So I accepted the PR with `pytest>=3.8.0` because earlier versions don't support the warning capture hooks used by the plugin, failing with an internal error. I hope this compromise works for you. And thanks for the PR!

**Comment by smarlowucf** [comment]
Thanks. I agree with minimum version for any breaking/unavailable features. The only breaking thing I noticed was the pytest warning class type which is only compared in the test suite so it seems okay to lower the limit.
