### ISSUE TITLE
Include indentation in the JSON report

### ISSUE THREAD

**Issue by jacebrowning** [numirias/pytest-json-report#8]
If this plugin called `json.dumps()` with `indent=2` it would help to make the report human readable.

Could this be the default or at least an option? Thanks!

**Comment by numirias** [comment]
Making it default is unfortunately not an option because the leading spaces will increase the report size even more. But I added `--json-report-indent` which you can use to supply an indentation level. I'll include it in the next release.

That said, you can also easily view or convert a JSON file to match your desired indentation, e.g. with [`json.tool`](https://docs.python.org/3/library/json.html#module-json.tool):

    python -m json.tool .report.json
